x = input('Digite algo: ')
print(type(x))
print('Alfanumérico:', x.isalnum())
print('Alfabético:', x.isalpha())
print('ASCII:', x.isascii())
print('Decimal:', x.isdecimal())
print('Dígito:', x.isdigit())
print('Identificador:', x.isidentifier())
print('Minúsculo:', x.islower())
print('Numérico:', x.isnumeric())
print('Printável:', x.isprintable())
print('Espaço:', x.isspace())
print('Título:', x.istitle())
print('Maiúsculo:', x.isupper())
